### ISSUE TITLE
[Feature] Determine aspect on max width and/or height

### ISSUE THREAD

**Issue by HMAZonderland** [eventviva/php-image-resize#18]
I'm developing an application where the image has to have a max width or max height. This way it will always be scaled correctly. Now I can enforce a width and height but it won't keep the aspect ratio.

Since I do not know in advance what the aspect ratio of the image is I cannot determine how the image should be scaled. 

Lets say I have a frame that is 145w and 90h (maximum dimensions). If i use resize it will force the image in this frame, rather than computing how much it should remove on either one dimension.

**Comment by cainmi** [comment]
Using `getSourceWidth` and `getSourceHeight` you can work out the aspect ratio, and decide to use `resizeToWidth` or `resizeToHeight`.

**Comment by HMAZonderland** [comment]
Perhaps you could add this as a function? :)

**Comment by cainmi** [comment]
I think it's out of the scope of this library, but it's up to @adityapatadia really.

Instead, you could extend the class:

```php
<?php

namespace HMAZonderland;

class ImageResize  extends \Eventviva\ImageResize
{
    public function getAspectRatio()
    {
        return $this->getSourceWidth() / $this->getSourceHeight();
    }
}


$r = new ImageResize('foo.jpg');

var_dump($r->getAspectRatio());
```

**Comment by adityapatadia** [comment]
Yes, rather than adding all the functionalities it is better that users extend the base class as per their requirement. The task that you are trying to achieve is very specific and library provides enough support to achieve that.

**Comment by adityapatadia** [comment]
@cainmi are we good to tag new version?

**Comment by cainmi** [comment]
I'll have a new PR through in a few hours, then tag it.
