### ISSUE TITLE
Losslessly compressing (png) support ?

### ISSUE THREAD

**Issue by gcmartijn** [eventviva/php-image-resize#20]
It seems that png images are nog losslessly.
The fact is that Google PageSpeed is complaining about it.

Do you think GD is able to do this ?

**Comment by cainmi** [comment]
PNGs that come out of GD do seem to have a bit of padding that can apparently be removed without losing image quantity, but I don't think it's within GD capabilities to do this.

I think you'll have to look as running something like OptiPNG.

**Comment by gcmartijn** [comment]
Found something, 

---
from php source (gd.h):

/* 2.0.12: Compression level: 0-9 or -1, where 0 is NO COMPRESSION at all,
* 1 is FASTEST but produces larger files, 9 provides the best
* compression (smallest files) but takes a long time to compress, and
* -1 selects the default compiled into the zlib library.
*/
Conclusion: Based on the Zlib manual (http://www.zlib.net/manual.html) the default compression level is set to 6.
---

if the compression is 9 I see some improvement, need to test is more.

**Comment by cainmi** [comment]
Yes you can set `$resize->quality_png = 9;` in this library, but I think it still won't pass PageSpeed.
