### ISSUE TITLE
Version 1.3

### ISSUE THREAD

**Issue by cainmi** [eventviva/php-image-resize#21]
Hey guys (especially @adityapatadia),

I've just pushed up a bunch of commits related to the changes we discussed in #19.

It was meant to be a new PR, but accidentally just pushed it to master.

Should be pretty stable though, and still getting passing all tests with 100% CC.

But please let me know if we need to change anything before tagging.

Majority of API stays the same, just the new `createFromString()` from @Sjaakmoes, which has been simplified a bit.

**Comment by adityapatadia** [comment]
What about removing one of the method? Are we going to leave both 'load' and 'create' methods?
