### ISSUE TITLE
Multiple operations on a single image does not work

### ISSUE THREAD

**Issue by dmromanov** [eventviva/php-image-resize#24]
```
$image = new ImageResize($file);
$image->resizeToWidth(100);
$image->crop(100, 100, true);
$image->save($smallFile);
````

Expected:
![expected](https://cloud.githubusercontent.com/assets/299059/6872011/96c9ca80-d4b7-11e4-9cf7-2458c6c90584.jpg)

What I get:
![test_3177788617](https://cloud.githubusercontent.com/assets/299059/6872069/c50f471c-d4b7-11e4-8efa-81ba0eafb92d.jpg)

**Comment by cainmi** [comment]
This class as it stands does not work with multiple operations, but you can extend it to do so:

```php
<?php

namespace Dmromanov;

require_once 'php-image-resize/src/ImageResize.php';

class ImageResize extends \EventViva\ImageResize
{

    public function compoundOperation()
    {
        return self::createFromString((string)$this);
    }

}

$image = new ImageResize('test.jpg');
$image
    ->resizeToWidth(100)
    ->compoundOperation()
    ->crop(100, 100, true)
    ->output()
;
```

However, you still won't get the result you're after, as when doing an enlarging crop, the class will first stretch it to fit, so you'll end up with this:

![image](https://cloud.githubusercontent.com/assets/392980/6878535/ceb0ed12-d533-11e4-9e30-526f97ad1dec.png)

**Comment by adityapatadia** [comment]
Can we improve library to achieve what @dmromanov is trying? I think it is intuitive functionality.. What are your views, let me know..

**Comment by Sjaakmoes** [comment]
We can, it actually makes more sense to have compound operations than the current behaviour but it could break the class for people who currently save a source image in multiple dimensions by chaining.

**Comment by cainmi** [comment]
Yes is probably does. If we go with SemVer then adding breaking changes while to bumping to 2.0 should be OK.

**Comment by dmromanov** [comment]
Hi guys! I want you to know that this is no more an issue for me as I've switched to another library a while ago.
Anyway, forbidding multiple operations (e.g. by throwing an exception) and noting this in the docs would be enough for me to close this issue.

**Comment by adityapatadia** [comment]
Any update one this one? Can we solve it?

**Comment by cainmi** [comment]
There are two issues here:

- Compound operations, which is possible by extending the class as per [this comment][0]
- Adding a resize to fit methods, which will be resolved by merging #26 

Adding native compound operations is also possible, but I think out of scope of this simple class. I don't have a problem with someone implementing it, but I don't really have the time.

For more complex image manipulation I tend to use something like [Intervention/image][1] anyway.

[0]: https://github.com/eventviva/php-image-resize/issues/24#issuecomment-87118499
[1]: https://github.com/Intervention/image

**Comment by adityapatadia** [comment]
Ok, so should we go ahead with merging #26? Let's leave first issue as it makes this library complex.

**Comment by cainmi** [comment]
Merged and resolved.
