### ISSUE TITLE
Compress to "x" MegaBytes

### ISSUE THREAD

**Issue by justfalias** [eventviva/php-image-resize#27]
Hi there,

Is there any way to compress the image setting, for example, as max file size 5 MB instead of setting quality parameter?

Thanks in advance

**Comment by cainmi** [comment]
You could try something like this:

```php
<?php

namespace Justfalias;

include 'ImageResize.php';

class ImageResize extends \Eventviva\ImageResize
{

    public function setQualityToFilesize($bytes)
    {
        if ($this->source_type == IMG_JPG) {
            $start = 100;
            $end = 0;
            $step = -10;
        } else if ($this->source_type == IMG_PNG) {
            $start = 0;
            $end = 9;
            $step = 1;
        } else {
            throw new \UnexpectedValueException('Expecting a JPG or PNG');
        }

        $quality = $start - $step;

        do {
            $quality += $step;

            $temp_image = tempnam(sys_get_temp_dir(), 'temp_image');
            $this->save($temp_image, null, $quality);
            $temp_size = filesize($temp_image);
        } while ($quality != $end && $temp_size > $bytes);

        if ($this->source_type == IMG_JPG) {
            $this->quality_jpg = $quality;
        } else {
            $this->quality_png = $quality;
        }

        return $this;
    }

}

$i = new ImageResize('img.jpg');
$i->setQualityToFilesize(1000000)->output(); // 1MB
```

There are a couple of problems with this though:

- The stepping isn't very intelligent
- [PHP GD](http://php.net/manual/en/book.image.php) isn't particularly good at handling large images - you will likely run in to memory or execution time issues

**Comment by justfalias** [comment]
Thanks for your work, but it gets stuck when running, and finally I can't get the compressed image. Anyway as you are saying I guess I could get some memory problems with large images.

**Comment by cainmi** [comment]
Try with a smaller (say 1MB) image, and then reduce it to 250KB (250,000B). This should work.
But I think larger images won't - they seem to use exponentially more memory while being process in GD, and will probably cause your script to run out of memory.

You're better off using an online image processing service, or processing the job on your server using some dedicated software.

**Comment by justfalias** [comment]
I can't test it right now. However I need it to compress from 5 to 20 MB file size images, so it won't fit to me. Thank you so much by the way
