### ISSUE TITLE
getimagesize fails if allow_url_fopen is Off with createFromString

### ISSUE THREAD

**Issue by Knallcharge** [eventviva/php-image-resize#30]
$image_info = @getimagesize($filename); in method __construct fails if allow_url_fopen is Off is php.ini, when using createFromString

this can be fixed with using getimagesizefromstring() in createFromString and transferring the data to __construct

**Comment by Knallcharge** [comment]
can't push, but here's the fix:

 src/ImageResize.php | 15 ++++++++++++---
 1 file changed, 12 insertions(+), 3 deletions(-)

diff --git a/src/ImageResize.php b/src/ImageResize.php
index 27dd6e2..3f5b254 100644
--- a/src/ImageResize.php
+++ b/src/ImageResize.php
@@ -49,7 +49,13 @@ class ImageResize
      */
     public static function createFromString($image_data)
     {
-        $resize = new self('data://application/octet-stream;base64,' . base64_encode($image_data));
+        $image_info = @getimagesizefromstring($image_data);
+
+        if (!$image_info) {
+            throw new \Exception('Could not read data');
+        }
+
+        $resize = new self('data://application/octet-stream;base64,' . base64_encode($image_data), $image_info);
         return $resize;
     }
 
@@ -57,12 +63,15 @@ class ImageResize
      * Loads image source and its properties to the instanciated object
      *
      * @param string $filename
+     * @param null $image_info
      * @return ImageResize
      * @throws \Exception
      */
-    public function __construct($filename)
+    public function __construct($filename, $image_info = null)
     {
-        $image_info = @getimagesize($filename);
+        if (is_null($image_info)) {
+            $image_info = @getimagesize($filename);
+        }
 
         if (!$image_info) {
             throw new \Exception('Could not read file');

**Comment by adityapatadia** [comment]
Can you create PR?

**Comment by Knallcharge** [comment]
Whatever that is.
I noticed that this only happens if allow_url_fopen ist set to false.

**Comment by adityapatadia** [comment]
Closing this. I will reopen if more people are facing the same issue.
