### ISSUE TITLE
Ability to crop in random position

### ISSUE THREAD

**Issue by Efiware** [eventviva/php-image-resize#31]
Hi

Thank you for a nice resizing tool. Would be great if you are able crop the image at a random position, i.e a method like this:

 public function crop($width, $height, $source_x, $source_y) {}

This will make this tool compatible with this client side cropping script: http://www.croppic.net/

**Comment by cainmi** [comment]
Maybe submit a PR?

**Comment by adityapatadia** [comment]
Added ```freecrop``` method. Refer readme.
