### ISSUE TITLE
Incorrect APP1 Exif Identifier Code

### ISSUE THREAD

**Issue by Knallcharge** [eventviva/php-image-resize#35]
When opening an image with incorrect EXIF-data, the error "Incorrect APP1 Exif Identifier Code" occurs (just a warning, but still).
A silencer for exif_read_data() would fix this. File: ImageResize.php, Line: 106

@see http://stackoverflow.com/questions/8106683/exif-read-data-incorrect-app1-exif-identifier-code

**Comment by adityapatadia** [comment]
Isn't the warning a right way to indicate that EXIF is invalid? I believe it should not be silenced.

**Comment by Knallcharge** [comment]
the silencer is just a workaround, the "right way" would be to throw an exception, not to output a warning which leaves the end-user puzzled and doesn't give the developer the chance to handle the error

**Comment by chrissachs** [comment]
just added a pull request to suppress the warnings #46

I agree with @adityapatadia that the more cleaner way would be to raise an Exception and handle it, but even cleaner way would be to not handle the "orientation fix" (https://github.com/eventviva/php-image-resize/commit/fd9cc21a3be5dc036e6b045cf00f4b5682dcf916) for all jpeg, and break/trigger a warning for images that worked before.

**Comment by adityapatadia** [comment]
Merged.
