### ISSUE TITLE
IMAGETYPE_* on save() method seems to replace all "png" occurrences in the filename

### ISSUE THREAD

**Issue by francesco14** [eventviva/php-image-resize#36]
My entry filename was "p18mq5j9k2op6amc1pngp1u1da37.png" and after I started

`$image_object->save(p18mq5j9k2op6amc1pngp1u1da37.png, IMAGETYPE_JPEG,90);`

filename turned to "p18mq5j9k2op6amc1jpgp1u1da37.jpg". Notice that there are two replacements in filename. I supposed that save() method can replace only the extension part of the filename.

How can I fix this issue?

**Comment by cainmi** [comment]
The `save` method does not touch the filename supplied.

I think you may have done a string replace earlier in your own code.

If you want to change between image formats, consider a regex that only replaces the end of your filename, or maybe [this](http://php.net/manual/en/function.pathinfo.php) function will help.

**Comment by francesco14** [comment]
Hi cainmi, thank you for your reply. You are right! It was my fault, sorry.
Anyway thanks for your link, sure it will help me.
