### ISSUE TITLE
Improve saving to string

### ISSUE THREAD

**Issue by michaelarnauts** [eventviva/php-image-resize#37]
The function `getImageAsString` saves the image to a temporary file on disk, just to read it again. This is not optimal. You can get the result in a string by using output buffering.

```php
<?php
ob_start();
imagepng($image);
$image_data = ob_get_contents();
ob_end_clean();
```

**Comment by gpaton** [comment]
But you will store your picture in memory, which may easily exceed memory_limit with big pictures

**Comment by michaelarnauts** [comment]
`imagepng` has to buffer the image in memory before writing it to disk, so I don't think the memory usage will increase, altough this can be checked with `memory_get_peak_usage`.

**Comment by gpaton** [comment]
OK, I've not watched carefully the whole function.
Are you sure that `imagepng`, by creating a new image, won't modify orignal image ?

Anyway, an improvement to your code is [possible](http://stackoverflow.com/a/19528944/3467996).

**Comment by adityapatadia** [comment]
Let me know if we want to implement in memory function. I request to evaluate pros and cons and memory usage. If everything seems fine, please create a PR.

**Comment by Sjaakmoes** [comment]
The string function used the output buffer before, it was changed in #19.

**Comment by adityapatadia** [comment]
@michaelarnauts changes made according to your suggestion with slight modification. Used ```php://temp``` instead of ```php://memory```

**Comment by adityapatadia** [comment]
Tests did not pass with 'php://temp' so reverted back. https://travis-ci.org/eventviva/php-image-resize/jobs/163143016

**Comment by michaelarnauts** [comment]
@adityapatadia The test failed because you didn't open the stream to `php://temp`.
The function `imagepng` expects the 2nd parameter to be a filename or an open stream, not just the string `php://temp`. If you `fopen()` first, it should work.

See http://php.net/manual/en/function.imagepng.php

**Comment by adityapatadia** [comment]
Would you mind creating a PR?
