### ISSUE TITLE
File size 0 when quality set

### ISSUE THREAD

**Issue by stephenvicino** [eventviva/php-image-resize#40]
I am loading and sizing images, however if I specify quality the image gets a file size of 0. This happens when I use `$image->quality_png = 50;` and `$image->save($tmp_name, IMAGETYPE_PNG, 50);`

But the images export fine with out setting a quality. 

My code:

`$image = new \Eventviva\ImageResize($_FILES['file']['tmp_name']);`

`$image->resizeToBestFit($image_size[0], $image_size[0]);`

`$image->save($tmp_name, IMAGETYPE_PNG, 50);`

**Comment by francesco14** [comment]
Hi Stephen, for IMAGETYPE_PNG you must set the "quality" with a number from 0 to 9.
In case of png images the quality value stands for compression level, 0 is for no compression (high quality).
