### ISSUE TITLE
Resize animated GIF file without destroying animation

### ISSUE THREAD

**Issue by prateekrc3** [eventviva/php-image-resize#44]
I am trying to resize a gif file but animation is destroyed.

```
<?php

require 'vendor/autoload.php';

$image = new \Eventviva\ImageResize("img/1460392243.gif");

var_dump($image);

$image->resizeToBestFit(500, 300);
$image->save("img/" . time().".gif");

?>
```

Please help !

**Comment by adityapatadia** [comment]
@cainmi can we do something for GIF resize? I searched on internet, there are a few libraries which tackles this issue.

**Comment by adityapatadia** [comment]
@prateekrc3 currently it is not possible as described in #9. We might work towards this.

**Comment by prateekrc3** [comment]
If library is unable to do so state it clearly in the README

**Comment by adityapatadia** [comment]
If you are annoyed by this, why not create a PR? I will merge.

**Comment by cainmi** [comment]
Using another library that handles GIFs would require a significant rewrite.

**Comment by adityapatadia** [comment]
Let's limit library functionality to static images only and not animated ones. It might change in future if we decide to do major rewrite.
