### ISSUE TITLE
Fatal error: Call to undefined function Eventviva\exif_read_data()

### ISSUE THREAD

**Issue by juanpablocs** [eventviva/php-image-resize#47]
when I upload a picture I get the following error

Fatal error: Call to undefined function Eventviva\exif_read_data()

../vendor/eventviva/php-image-resize/src/ImageResize.php on line 106

**Comment by adityapatadia** [comment]
The issue is already pointed by #43 Can you tell me which PHP version do you use? I will release new version to fix this in 8-10 hours.

Thanks,

**Comment by juanpablocs** [comment]
thanks, temporary solution with my code

```
if(!function_exists('exif_read_data'))
        return $img;
....
```

**Comment by adityapatadia** [comment]
New version 1.5.4 fixes this.

**Comment by rakshazi** [comment]
@adityapatadia please, update info about package on packagist.org, because only version 1.5.3 is available as stable in composer for now

**Comment by adityapatadia** [comment]
I can see 1.5.4 in packagist. https://packagist.org/packages/eventviva/php-image-resize. Did you use exact number 1.5.3 in your composer file?

**Comment by rakshazi** [comment]
@adityapatadia no, I just use "@stable" as version

**Comment by adityapatadia** [comment]
It should work. Can you try 1.5.* ?

**Comment by rakshazi** [comment]
It works good for now. Thank you!

ср, 15 июн. 2016 г. в 10:27, Aditya Patadia <notifications@github.com>:

> It should work. Can you try 1.5.* ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/eventviva/php-image-resize/issues/47#issuecomment-226109391>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADRO9xQHOq3pGeyRwfEAP6J_hfwxAouLks5qL6l8gaJpZM4IoEb9>
> .
>
-- 
Best regards,
Nikita Chernyi (Backend Developer, DevOps).

about.me/nikus
<https://about.me/nikus?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by tarhe** [comment]
I am using "eventviva/php-image-resize": "1.5.*" and I am still getting this error

local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function Eventviva\exif_read_data()' in /home/mywebiste/vendor/eventviva/php-image-resize/src/ImageResize.php:106

**Comment by adityapatadia** [comment]
Please provide more information about system and platforms. Your sample code will also help.

**Comment by rakshazi** [comment]
Symfony error handler handles level 0 (muted with `@`) errors. Just set dummy error handler before and restore error handler after image manipulations

**Comment by rakshazi** [comment]
If you need example - ping me

**Comment by tarhe** [comment]
I am using Laravel 5.2 

 // resize
        $image_resize = ImageResize::createFromString($imagedata);
	$image_resize->quality_jpg = 100;
        $image_resize->resize(200, 200);	
        $image_resize->save( base_path() . '/images/' . $image_new_name . '.' . 'jpg' );

$image_new_name is a variable with a name.

@rakshazi Please, I need an example.

**Comment by rakshazi** [comment]
@tarhe 
You need install php extension `exif` and `gd`, in alpine linux it will be (for php7): `php7-exif php7-gd`,
after that you need do following to fix "heisenbug" with corrupted image metadata, just use following code and all we'll be ok:
```php
protected function resizeImage(string $image_new_name)
    {
        /**
         * Framework will throw ErrorException exif_read_data(image.jpg): Illegal IFD size
         * for some files, but these errors must be muted (@exif_read_data($filename))
         * that's why we set dummy error handler
         */
        set_error_handler(function ($level, $message, $file, $line) {
            //Do nothing
        });
        $image_resize = ImageResize::createFromString($imagedata);
        $image_resize->quality_jpg = 100;
        $image_resize->resize(200, 200);

        $image_resize->save( base_path() . '/images/' . $image_new_name . '.' . 'jpg' );
        /**
         * Disable our dummy error handler
         */
        restore_error_handler();
    }
```

**Comment by tarhe** [comment]
@rakshazi Thanks, I appreciate
