### ISSUE TITLE
What license is your PHP image resize class?

### ISSUE THREAD

**Issue by bitpage-de** [eventviva/php-image-resize#49]
I would like to use your great class in our commercial product, but I cannot find your licensed defined anywhere. 
If no license is defined, the normal copyright (All rights reserved) comes into action and anybody - no matter if the usage is private or commercial - has to ask you.

So may I ask you if I can use it for our commercial product or set it generally under a license you prefer?

Thanks in advance and keep up your great work!

**Comment by bitpage-de** [comment]
I am happy I found your license definition at the composer.json file and that it is MIT! Thank you for sharing your great work under MIT license. So what about writing the license hint in the readme.md or an extra license.md  file like [suggested by github](https://help.github.com/articles/open-source-licensing/)?

**Comment by adityapatadia** [comment]
Yes, it is MIT licensed but it would be great if you can share which product is using it so community has more confidence in library.

You can create PR to add licence information as well as your product info in readme.md.
