### ISSUE TITLE
IMAGETYPE_WEBP is not recognized

### ISSUE THREAD

**Issue by elyorm** [eventviva/php-image-resize#51]
I am trying to add _webp_ image file type like

```
elseif ($this->image_type == IMAGETYPE_WEBP) {
 $this->image = imagecreatefrompng($filename);
}
```

but it gives me error. could anyone tell me how to add _webp_ file type?

**Comment by adityapatadia** [comment]
Any update here? I would close it if there is no more issue here.

**Comment by asv1979** [comment]
Hello, i got same error.
"gumlet/php-image-resize": "2.0.1"
"php": "^7.4"

use Gumlet\ImageResize;
final class CompressImageBehavior extends Behavior
$image->quality_png = $this->qualityImagePng;

$image = new ImageResize($imagePath);
$image->resizeToWidth(1280);
$image->resizeToHeight(1280);
$image->save($this->imagePath);

imagecreatefrompng(): gd-png: libpng warning: Interlace handling should be turned on when using png_read_image
vendor/gumlet/php-image-resize/lib/ImageResize.php   line 155
