### ISSUE TITLE
Size of PNG too big after resize

### ISSUE THREAD

**Issue by ckissi** [eventviva/php-image-resize#52]
Hi,

I've tried to resize PNG image to the smaller size (with resizeToWidth) but the resulting image was extremely big. When I've used image compress tool (ImageOptim) it was able to remove 99% of the image size so there must be too much bloating information in the image.

**Comment by adityapatadia** [comment]
You should use quality parameter for PNG compression. https://github.com/eventviva/php-image-resize#quality It does not apply compression by default.
