### ISSUE TITLE
JPG results in unspecified error

### ISSUE THREAD

**Issue by bmorerob** [eventviva/php-image-resize#54]
When I upload a jpg using the class my site errors and goes to a blank screen (no error message). The class works fine on my local dev environment, it only breaks on the remote host, and only then when uploading jpgs.

**Comment by adityapatadia** [comment]
Which method of library you use? Please also post error log here so we can debug.

**Comment by bmorerob** [comment]
Sorry, what do you mean by which library?

**Comment by adityapatadia** [comment]
I mean which function do you use? Can I see your sample code? If error does not come, how do you know it breaks? There must be something in PHP error logs.

**Comment by markifornia** [comment]
This may be related to the issue I opened #55. 

In my case, I was running into errors more frequently on my mobile phone. The solutions I've provided fixed the issue.

**Comment by bmorerob** [comment]
I seem to have fixed the problem but I'm not 100% sure how. I updated the php modules and the problem resolved.

**Comment by adityapatadia** [comment]
Cool, closing the issue.
