### ISSUE TITLE
Memory Limit Error and Error Suppression 

### ISSUE THREAD

**Issue by markifornia** [eventviva/php-image-resize#55]
This is a great tool, thanks for developing this module. 

I have encountered some bugs however. I hope it would improve the current code base. I noticed in one of the recent commits - errors are suppressed. However, there are other areas of the code where errors need to be suppressed. 

I have added the setting below. However, I do understand that errors are useful in development (not production!) settings. 

```
ini_set ('gd.jpeg_ignore_warning', 1);
```

I also encountered an memory limit specifically related to the following code block. The imagerotate function bugs out when the memory limit exceeds 94371840 bytes. So I have also included the setting below.

```
ini_set('memory_limit', '300M'); // add this

if ($orientation === 6 || $orientation === 5){
        $img = imagerotate($img, 270, null);

...
```

Perhaps this module could include some sort of logic around these two cases. Most PHP frameworks provide an environment variable, perhaps this can be hooked in somewhere.

**Comment by adityapatadia** [comment]
We can't add the memory limit or warning suppression setting in library. It's good to use such settings in your own code. I would close this issue as they are not something which we can implement in library.

**Comment by chiragpurohit71085** [comment]
What is the solution for this. I am still facing this issue. I am running php on ec2 instance. I have tried to upload image file with 5 mb

I have set 

memory_limit | 128M

upload_max_filesize | 10M


<br />
<b>Fatal error</b>:  Out of memory (allocated 75497472) (tried to allocate 36864 bytes) in
<b>/web_api/vendor/eventviva/php-image-resize/lib/ImageResize.php</b> on line
<b>137</b>
<br />
<br />
<b>Fatal error</b>:  Out of memory (allocated 75497472) (tried to allocate 32768 bytes) in
<b>/web_api/system/core/Exceptions.php</b> on line
<b>1</b>
<br />

**Comment by chiragpurohit71085** [comment]
If any body is still facing the issue, I found chaining method and followed that. I have to upload multiple files and resize so I have done as follow

foreach ($_FILES as $key => $val) {
...........

			$image = new \Eventviva\ImageResize($original_target_file);
			
			$image->resizeToBestFit($this->thumb_image_width, $this->thumb_image_height)
			->save($thumb_target_file)
			
			->resizeToBestFit($this->app_image_width, $this->app_image_width)
			->save($app_target_file)
			
			->resizeToBestFit($this->big_image_width, $this->big_image_height)
			->save($big_target_file);

Hope that helps.Thanks for making such a wonderful lib.

**Comment by adityapatadia** [comment]
This is good solution. The memory limits are put in place for a reason and the chaining methods allow for efficient use of memory. Thanks @chiragpurohit71085 for posting this.

**Comment by markifornia** [comment]
@chiragpurohit71085 thanks for providing the fix, that is a better solution than the one I proposed. Could this be something that can be added to the master library?
