### ISSUE TITLE
how to destroy & reuse image variable?

### ISSUE THREAD

**Issue by primarycare** [eventviva/php-image-resize#57]
thank you for this script & your hard work.

i am using your script in a php loop with an array of images to be uploaded and resize

since for each image, i will use the same variable 

$image = new \Eventviva\ImageResize("$image_src");
(where $image_src is an image source which is run in php loop)

your script will not run on the next image. I am thinking it is because the $image is not being cleared for a new source

i tried:
$image = "";
unset($image);
and destroy($image)

but none of these work. How do i destroy & reuse the variable for a new image source?

**Comment by adityapatadia** [comment]
That is weird. Can you post the loop?

**Comment by primarycare** [comment]
Sorry, i found the error in my php loop. Your script works perfectly.
Consider closed
