### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Nadstation** [eventviva/php-image-resize#61]
Hi all,

I hope you re all fine .
I need help to use your library. 
I don't user composer so I do as you mentioned :

" ...
Otherwise:
include '/path/to/ImageResize.php';
Because this class uses namespacing, when instantiating the object, you need to either use the fully qualified namespace:
$image = new \Eventviva\ImageResize(); 
..."

At this line I get a 500 Internal Server Error : 
$image = new \Eventviva\ImageResize(); 
OR when I alias it 
use \Eventviva\ImageResize;
$image = new ImageResize(); <--- this line 

I included this way:

include "../../../includes/imageResize/lib/ImageResize.php"; 
use \Eventviva\ImageResize;

Is the something I missed ?

Thank you in advance for your answer.

**Comment by adityapatadia** [comment]
Let me know the exact error. It will help solve problem. You can get it from server logs.
