### ISSUE TITLE
Bigger png size after resizing

### ISSUE THREAD

**Issue by xzdshr** [eventviva/php-image-resize#63]
Hello!
When you resizing png with transparent background - it is important to maintain small file size.
For example:
 - original image.png (350x700px 76 KB)
 - resized image.png (265x535px 200KB)

It happens because of increasing amount of colors in palette. Under 1000 in original image / more than 8000 in resized.

Fast dirty hack to avoid it:
`$image_type = $image_type ?: $this->source_type;`
`if($image_type == IMAGETYPE_PNG) {`
`    $dest_image = imagecreate($this->getDestWidth(), $this->getDestHeight()); // not true color!`
`    $alpha = imagecolorallocatealpha($dest_image, 255, 255, 255, 127); // fully transparent white color`
`    imagefill($dest_image, 0, 0, $alpha); // fill image with transparent background`
`} else {`
`    $dest_image = imagecreatetruecolor($this->getDestWidth(), $this->getDestHeight());`
`}`

 - resized image.png without true color (265x535px 56KB)

Maybe you will implement some sort of feature, based on this.

**Comment by adityapatadia** [comment]
Can you create proper PR for this?

**Comment by xzdshr** [comment]
I tested this on 1000 images and some of them becomes corrupted (bad colors).
I will create PR once I do proper algorhythm and backward compatibility.

**Comment by adityapatadia** [comment]
Sure. Take your time. I will try to merge asap.
