### ISSUE TITLE
PNG ImageSaveAlpha

### ISSUE THREAD

**Issue by VertigoRay** [eventviva/php-image-resize#69]
Would be great if PNG supported the [`imagesavealpha` function](https://secure.php.net/manual/en/function.imagesavealpha.php).

If it's not something you want to poke at, I'll look at the code. Should be easy enough to implement. 🍻

**Comment by adityapatadia** [comment]
If you can implement along with unit tests, I would be prompt to merge and release version.

Regards,
Aditya Patadia

**Comment by adityapatadia** [comment]
https://github.com/eventviva/php-image-resize/blob/master/lib/ImageResize.php#L176 check this. We already support it.
