### ISSUE TITLE
Problem with transparent PNG

### ISSUE THREAD

**Issue by williamcastro** [eventviva/php-image-resize#73]
I'm having issues to generate a thumbnail from a Transparent PNG.
Someone have some idea how to solve this problem?

**Comment by adityapatadia** [comment]
Your question is very vague. It would be great if you can provide code you are using and sample image.

**Comment by williamcastro** [comment]
@adityapatadia Sorry for the vague question, the code i'm using to generate thumbnails is that above:

```php
<?php
          $image = new \Eventviva\ImageResize($img_path);
	  $image->resizeToWidth(560);
	  $image->save($thumb_path, null, 95);

````

The code is working perfectly with JPG, but I had the problem with this image (PNG) https://drive.google.com/file/d/0B8w3Z6QVAtrwVkZzdFo0SkVPVVE/view?usp=sharing

I tried to generate the thumbnail with a smaller PNG transparent, and haven't success.

Thank you for your help!

**Comment by g33kme** [comment]
I have the same problem. I can not create a thumb from a PNG source file. Can anybody help?
(using the same code as williamcastro describes)

**Comment by g33kme** [comment]
I got it: based on http://www.php.net/manual/en/function.imagepng.php you can only set a quality up to 9 for PNG images. So you have to take care about the quality param depending on JPG or PNG
