### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by MarcelHekkert** [eventviva/php-image-resize#75]
The class looks fine. It would be a benefit to have a caching feature. It could be based on a CONST save_path. If it is set, it can check if the image exists. If it does, directly return the image.
Optional: A no_cache on the API request in case of new settings for the same dimensions while maintaining a save_path.

It would greatly expand on projects this class could be used for.

**Comment by adityapatadia** [comment]
Can you explain in detail what would be use cases for such caching feature? If you can help implement it and create a PR, it would be great too.

**Comment by adityapatadia** [comment]
I will reopen if there is valid use case for it.
