### ISSUE TITLE
Fatal error: Uncaught Eventviva\ImageResize

### ISSUE THREAD

**Issue by c3x** [eventviva/php-image-resize#77]
I run into an very strange problem.

I have an upload script, that will be start through the form from the upload page. So, this script runs "stand alone". Then I have an import area in my project. This import is included into an other (main) file.

When I upload an file, everything is fine. ImageResize do what it should do.

When I import the images, I got this error message:

`
Fatal error: Uncaught Eventviva\ImageResize
Exception: Could not read file in /home/sites/dev/admin/classes/ImageResize.php:32 

Stack trace: 
#0 /home/sites/dev/admin/content_photo_import.php(130): Eventviva\ImageResize->__construct('/home/sites/dev...') 
#1 /home/sites/dev/admin/dashboard.php(57): include('/home/sites/dev...') 
#2 /home/sites/dev/admin/index.php(48): include('/home/sites/dev...') 
#3 {main} thrown in /home/sites/dev/admin/classes/ImageResize.php on line 32
`

The path's are in both cases the same. The only different is, on the upload script I use "move_uploaded_file($tmp, $newFilePath" and on the import script, I use "copy($file, $newFilePath".

Any idea how to fix?

Regards
Torsten

**Comment by c3x** [comment]
In both cases the scripts are started through a form POST call.

But for the upload form, the code is into an separate PHP file. The import has all the code into the same file.

**Comment by TheM1984** [comment]
Can you verify that the files are being copied? And that php has permissions for the files and the new location?

What are the return values of the move_uploaded_file and the copy?
They should both return true if the copy or move action is successfull.

**Comment by c3x** [comment]
Also in both cases, the images are on the right place - coz, I can access them, after the upload/import process is finished. Also I can edit the images, coz I have an option to select one of the images as cover photo and I rename this file to a new name.

The only thing that's not work, if I want to resize the images directly after the copy process. After the upload process, it works.

**Comment by adityapatadia** [comment]
Closing this issue for now. Let me know if the problem still needs attention.
