### ISSUE TITLE
[FEATURE REQUEST] PSR Standards

### ISSUE THREAD

**Issue by brianfreytag** [eventviva/php-image-resize#87]
I'd like to see this library get updated to utilize PSR standards. 

One major thing I've noticed is that part of the library utilizes tab characters and others utilize 4 space indentation.

If I get a little free time, I will happily take a look at updating all of the variables, method definitions, spaces, etc... and put in a PR. I just want to know if there is any support for this from the maintainers. 1 or 2 thumbs up will be enough for me to put this on my "to-do" list.

**Comment by adityapatadia** [comment]
Just ensure that you write unit tests accordingly. Target is also there to keep majority of code covered by unit tests.

**Comment by brianfreytag** [comment]
Given that PSR (PHP Style Recommendations) are  just coding-style changes, I don't see these changes breaking any of the unit tests, but I will certainly ensure that they don't. I will also apply PSR standards to the unit tests.

**Comment by adityapatadia** [comment]
I think most of these changes were applied in https://github.com/eventviva/php-image-resize/pull/91

Closing this issue. If something is left, I will reopen later.

**Comment by rakshazi** [comment]
I suggest you to use php-cs-fixer tool for autofix codestyle (not only psr 1/2), just use it in pre-commit hook
