### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by dogseven** [eventviva/php-image-resize#88]
I get the following error:
Fatal error: 
Uncaught exception 'Eventviva\ImageResizeException' with message 'File does not exist' in /home/mysite/public_html/inc/imageresize.php:72 
Stack trace: 
#0 /home/mysite/public_html/inc/savephotos.php(54): Eventviva\ImageResize->__construct('')
#1 /home/mysite/public_html/my-details/mydetails/myhome/photosandpanoramas.php(17): include('/home/mysite/pu...') 
#2 {main} thrown in /home/mysite/public_html/inc/imageresize.php on line 72

This only appears with larger files - I am testing with an image 3.5M, which will be resized after uploading. I followed up with a 708k file which uploaded without issue.

Users can upload up to 8 images, and sometime use files as large as 6 or 7Mb, so the server is set to
post_max_size   70M
upload_max_filesize   8M

I understand that the file may be in a different place to the expected place - but I can't see how to find what the filename currently is, or where it should be! And, if a smaller file gets through, then I think that is less likely to be the issue.

**Comment by adityapatadia** [comment]
I feel its more of a file path problem than library problem. Can you check with 8 MB file saved on disk to check? That way you can be sure that its about different file path.

**Comment by dogseven** [comment]
In message <eventviva/php-image-resize/issues/88/322008266@github.com>,
Aditya Patadia <notifications@github.com> writes
>I feel its more of a file path problem than library problem. Can you check with 
>8 MB file saved on disk to check? That way you can be sure that its about 
>different file path.

Unfortunately, I ran out of time, and had to use a different uploader.

Thanks for you suggestion, it is appreciated.
-- 
Pete Clark

http://www.hotcosta.com
The towns and villages of Spain - and what's happening there
