### ISSUE TITLE
Suppress exif_read_data() errors

### ISSUE THREAD

**Issue by avataru** [eventviva/php-image-resize#92]
exif_read_data() can sometimes generate errors and should be suppressed. The same suggestion is made in a [comment](https://stackoverflow.com/a/45750034) to the SE post that served as inspiration for the imageCreateJpegfromExif() method.

**Comment by adityapatadia** [comment]
It's already implemented in library. Are you using latest version?

**Comment by hultberg** [comment]
@adityapatadia I think your misunderstanding @avataru, he is talking about php errors that one can not catch, but is just outputed directly. Thats why it should be supressed in this library, as you later checks if the data was retrieved. I opened #93

**Comment by hultberg** [comment]
@adityapatadia Thanks for merging #93, could you please release a patch version to include the fixes?

**Comment by avataru** [comment]
Thank you @hultberg and @adityapatadia

**Comment by adityapatadia** [comment]
done!
