### ISSUE TITLE
quality_jpg doesn't work

### ISSUE THREAD

**Issue by Machou** [eventviva/php-image-resize#95]
i use quality_jpg to 10, but doesn't work

my code :

```
<?php
$image = new \Eventviva\ImageResize('img1.jpg');
$image->quality_jpg = 10;
$image->resize(215, 290);
$image->save('img2.jpg');
?>
```

Resize work, but not quality.

**Comment by adityapatadia** [comment]
Can you try this?
``` $image->save('img2.jpg', $quality=10) ```

Your code should also work, I don't know why it does not work. Check the source code here how it is used: https://github.com/eventviva/php-image-resize/blob/master/lib/ImageResize.php#L244

**Comment by Machou** [comment]
Sorry, the code work now.

i don't know what i change... but work. :P
